# Generated by Django 3.2.14 on 2022-07-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokuser',
            options={'permissions': [('imitate', 'Can imitate me')]},
        ),
    ]
