lok:
  issuer: lok
  key_type: RS256
  public_key: YOUR_PUBLIC_KEY
port: 8090
postgres:
  db_name: rekuest_db
  host: daten
  password: YOUR_DB_PASSWORD
  port: 5432
  user: YOUR_DB_PASSWORD
rabbit:
  host: YOUR_RABBIT_HOST
  password: YOUR_RABBIT_PASSWORD
  port: 5672
  username: YOUR_RABIT_USERNAME
  v_host: ""
redis:
  host: redis
  port: 6379
server:
  admin:
    email: a_fake@email.com
    password: admin
    username: admin
  debug: true
  hosts:
    - "*"
  secret_key: DJANGO_SECRET_KEY
