version: "3.4"

services:
  arkitekt:
    build: .
    command: bash run.sh
    ports:
      - 8090:8090
    depends_on: 
      - redis
      - mister
      - baberl
  baberl:
    image: postgres:12.6-alpine
    environment: 
      POSTGRES_DB: hello_baberl
      POSTGRES_PASSWORD: hello_baberl
      POSTGRES_USER: hello_baberl
  mister:
    image: jhnnsrs/mister:fancy
    hostname: localhost
    command: rabbitmq-server
    ports:
       - 5672:5672
       - 15672:15672
  redis:
    image: redis:latest
    ports:
      - 6379:6379



networks:
  default:
    external:
      name: dev

