version: "3.4"

services:
  arkitekt:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - 8090:8090
    volumes:
      - .:/worskpace:cached
    env_file:
      - elements.env
  baberl:
    image: postgres:12.6-alpine
    env_file:
      - elements.env



networks:
  default:
    external:
      name: dev

