version: "3.4"

services:
  arkitekt:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - 8090:8090
    volumes:
      - .:/worskpace:cached
    env_file:
      - elements.env
  baberl:
    image: postgres:12.6-alpine
    env_file:
      - elements.env
  mister:
    image: jhnnsrs/mister:fancy
    hostname: localhost
    command: rabbitmq-server
    ports:
       - 5672:5672
       - 15672:15672
  redis:
    image: redis:latest
    ports:
      - 6379:6379



networks:
  default:
    external:
      name: dev

