version: "3.4"

services:
  arkitekt:
    build: .
    command: bash run.sh
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace
    ports:
      - 8090:8090

networks:
  default:
    external:
      name: dev
