"""
Django settings for kreature project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from .configuration import Settings
from .logs import build_logging


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.django.secret_key  # TODO: Change this in production

# SECURITY WARNING: don't run with debug turned on in production!
# Config-driven and defaulting to False. This is load-bearing beyond leaking tracebacks:
# authentikate only refuses static tokens when DEBUG is False (see its settings.py), so a
# hardcoded DEBUG=True silently disables that guard.
DEBUG = conf.django.debug

ALLOWED_HOSTS = conf.django.hosts

AGENT_HEARTBEAT_INTERVAL = 10
AGENT_HEARTBEAT_RESPONSE_TIMEOUT = 5

# Seconds without a heartbeat after which a ``connected`` agent is presumed dead. The single
# window unifying every liveness decision (reconnect gate, availability query, GraphQL
# ``active`` field, healing reaper) — see ``facade.liveness``. 3× the heartbeat interval, so a
# live agent must miss two heartbeats before it is stale.
AGENT_STALE_AFTER = 3 * AGENT_HEARTBEAT_INTERVAL

# Redis endpoint the agent queue (broadcast -> agent delivery) talks to.
AGENT_REDIS_HOST = conf.redis.host
AGENT_REDIS_PORT = conf.redis.port
# Namespace of every first-party redis key — see ``facade.redis_keys``.
REDIS_KEY_PREFIX = conf.redis.key_prefix

# HookAgent HTTP signatures — see ``facade.hooks``.
HOOK_SIGNATURE_MODE = conf.rekuest.hook_signature_mode
HOOK_MAX_SKEW = conf.rekuest.hook_max_skew


AGENT_HEARTBEAT_NOT_RESPONDED_CODE = 3001

# Reclaim grace window (seconds). On a disconnect the failure/cascade is delayed this long so
# a brief blip can reclaim same-session in-flight work before it fires. 0 means no grace
# (strict). ``PHYSICAL`` overrides the window for effect:physical work, which may warrant a
# shorter (or zero) window than freely-retryable effect:none work. Consumed by the
# reclaim/grace backend via ``facade.deadlines.grace_seconds``.
REKUEST_GRACE = {
    "DEFAULT": conf.rekuest.grace_default,
    "PHYSICAL": conf.rekuest.grace_physical,
    # Progress lease (seconds): a physical task that has reported progress but then
    # goes silent this long — while its agent is still connected (wedged-but-alive) — is
    # failed as terminal. 0 disables the lease (default).
    "PROGRESS_LEASE": conf.rekuest.progress_lease,
    # None of these windows is a timer: each starts at a DB column and is enforced by the
    # in-process sweep (``facade.reaper``), every SWEEP_INTERVAL seconds, on whichever
    # backend gets there first. See ``facade.deadlines`` for the accessors.
    "SWEEP_INTERVAL": conf.rekuest.sweep_interval,
    # A dispatched task its live agent never reports on: redelivered once, then CRITICAL.
    "PICKUP_DEADLINE": conf.rekuest.pickup_deadline,
    # DISCONNECTED ("fate unknown") stays recoverable this long, then is finalized.
    "DISCONNECTED_EXPIRY": conf.rekuest.disconnected_expiry,
    # Unconfirmed cancel → interrupt → finalized. A request's own ``auto_interrupt`` wins.
    "CONTROL_DEADLINE": conf.rekuest.control_deadline,
}

# Task retention: terminal root task trees older than this are deleted by the retention
# sweep (the in-process reaper loop). 0 disables — history then grows forever.
TASK_RETENTION_SECONDS = conf.rekuest.task_retention

# Probes (facade.probes): redis-held, zero-DB-row invocations. TTL is the garbage
# collector — a live probe's state expires after PROBE_TTL_SECONDS without a write, and a
# terminal probe lingers PROBE_LINGER_SECONDS for late subscribers.
PROBE_TTL_SECONDS = conf.rekuest.probe_ttl
PROBE_LINGER_SECONDS = conf.rekuest.probe_linger
PROBE_MAX_INFLIGHT_PER_CALLER = conf.rekuest.probe_max_inflight

# Application definition
USE_X_FORWARDED_HOST = conf.django.use_x_forwarded_host


INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "guardian",
    "channels",
    "authentikate",
    "django_probes",
    "datalayer",
    "kante",
    "facade",
    "health_check",  # required
]

# Authentikate section

AUTH_USER_MODEL = "authentikate.User"

AUTHENTIKATE = conf.authentikate.model_dump()


# Provenance issuer section
#
# Rekuest mints a signed (Ed25519) provenance JWT at dispatch and publishes
# the verifying key at the JWKS endpoint (see ``rekuest/urls.py``). Loaded from the
# ``provenance`` block of config.yaml; a static ``provenance.private_key`` is
# required — the facade refuses to start without it (see facade/provenance/keys.py).
PROVENANCE = {
    "ISSUER": conf.provenance.issuer,
    "KID": conf.provenance.kid,
    "PRIVATE_KEY": conf.provenance.private_key,
    "PUBLIC_KEY": conf.provenance.public_key,
    "TOKEN_TTL_SECONDS": int(conf.provenance.token_ttl_seconds),
    "HUMAN_ROLES": list(conf.provenance.human_roles),
    "STRICT": bool(conf.provenance.strict),
}


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis chasnnel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        # ``prefix`` namespaces every group/channel key: it MUST be unique per service on a
        # shared redis (it used to be a copy-pasted "mikro" across most of the stack).
        # ``capacity`` is NOT per socket: channels_redis multiplexes every consumer of a
        # process onto one receive queue, and silently drops what does not fit.
        "CONFIG": {
            "hosts": [(conf.redis.host, conf.redis.port)],
            "prefix": conf.redis.channel_prefix,
            "capacity": conf.redis.channel_capacity,
            "expiry": 60,
        },
    },
}

STRAWBERRY_DJANGO = {
    "USE_DEPRECATED_FILTERS": True,
    "DEFAULT_PK_FIELD_NAME": "id",
}

# Semantic search (the vendored ``embeddings`` package). Actions embed their name +
# description into a pgvector column on save, with a model2vec static model that runs in this
# process (no service, no GPU, ~1 ms per row). ``ActionFilter.search`` ORs "cosine distance
# below DISTANCE_THRESHOLD" onto its substring match. DIMENSIONS is also the width of the
# database column: the ``embeddings`` system checks refuse to start when the model, this
# setting and the column disagree. Rows filled by another model are re-embedded from the
# reaper tick (``facade.reaper``), never by a command.
EMBEDDINGS = {
    "ENABLED": conf.embeddings.enabled,
    "MODEL": conf.embeddings.model,
    "MODEL_PATH": conf.embeddings.model_path,
    "DIMENSIONS": conf.embeddings.dimensions,
    "DISTANCE_THRESHOLD": conf.embeddings.distance_threshold,
    "SWEEP_INTERVAL": conf.embeddings.sweep_interval,
    "SWEEP_BATCH_SIZE": conf.embeddings.sweep_batch_size,
}


CSRF_TRUSTED_ORIGINS = conf.django.csrf_trusted_origins
# Consumed by kante's ``dynamicpath``/``re_dynamicpath`` (see rekuest/urls.py), which prefixes
# each URL pattern itself. Deliberately NOT Django's FORCE_SCRIPT_NAME — setting both would
# prefix twice.
MY_SCRIPT_NAME = conf.django.force_script_name


CORS_ALLOW_ALL_ORIGINS = True


DATALAYER = conf.datalayer.model_dump(exclude_none=True) if conf.datalayer else {}


ROOT_URLCONF = "rekuest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rekuest.wsgi.application"
ASGI_APPLICATION = "rekuest.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Console logging: one plain line per record on root; see logs.py. ``LOG_LEVEL=DEBUG``
# (env) brings back per-event detail; ``django.enable_rich_logging`` renders with rich.
LOGGING = build_logging(
    level=os.environ.get("LOG_LEVEL", conf.django.log_level),
    rich=conf.django.enable_rich_logging,
)
