# Generated by Django 3.2.8 on 2021-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='interfaces',
            field=models.JSONField(default=[], help_text='Intercae that we ahdere to'),
        ),
    ]
