# Generated by Django 3.2.18 on 2023-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port_groups',
            field=models.JSONField(default=list, help_text='Intercae that we use to interpret the meta data'),
        ),
    ]
