# Generated by Django 6.0.3 on 2026-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="required_locks",
            field=models.ManyToManyField(
                blank=True,
                help_text="The agent's locks this implementation takes while it runs (declared as its `locks`).",
                related_name="required_by",
                to="facade.lock",
            ),
        ),
    ]
