# Generated by Django 3.1.7 on 2021-04-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20210428_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('level', models.CharField(choices=[('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level')], default='INFO', max_length=200)),
                ('reservation', models.ForeignKey(help_text='The reservation this log item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='facade.assignation')),
            ],
        ),
    ]
