# Generated by Django 3.1.7 on 2021-04-09 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0002_auto_20210329_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The creator is this assignation', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provision',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='This provision creator', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='This provision creator', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
