# Generated by Django 3.1.7 on 2021-03-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20210304_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.OneToOneField(help_text='The Associated Service for this Provider', on_delete=django.db.models.deletion.CASCADE, to='facade.service'),
        ),
    ]
