# Generated by Django 3.2.2 on 2021-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionlog',
            old_name='reservation',
            new_name='provision',
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Request has been created and waits for its initial creation)'), ('PROVIDING', 'Providing (Request has been send to its Provider and waits for Result'), ('ACTIVE', 'Active (Provision is currently active)'), ('CANCELING', 'Cancelling (Provisions is currently being cancelled)'), ('LOST', 'Lost (Subscribers to this Topic have lost their connection)'), ('RECONNECTING', 'Reconnecting (We are trying to Reconnect to this Topic)'), ('DENIED', 'Denied (Provision was rejected for this User)'), ('ERROR', 'Error (Reservation was not able to be performed (See StatusMessage)'), ('CRITICAL', 'Critical (Provision resulted in an critical system error)'), ('ENDED', 'Ended (Provision was cancelled by the Platform and will no longer create Topics)'), ('CANCELLED', 'Cancelled (Provision was cancelled by the User and will no longer create Topics)')], default='PENDING', help_text='Current lifecycle of Provision', max_length=300),
        ),
    ]
