# Generated by Django 3.1.7 on 2021-03-15 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20210312_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, help_text='A Unique identifier for this Commision', unique=True)),
                ('pod', models.ForeignKey(help_text='Which pod are we commisssioning?', on_delete=django.db.models.deletion.CASCADE, related_name='commisions', to='facade.pod')),
            ],
        ),
    ]
