# Generated by Django 3.2.8 on 2022-01-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_node_interfaces'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('params', 'node', 'template', 'app', 'creator'), name='Equal Reservation on this App by this User is already in place'),
        ),
    ]
