# Generated by Django 3.1.7 on 2021-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20210224_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='version',
            field=models.CharField(default=0.1, help_text='The version of the bergen API this endpoint uses', max_length=100),
            preserve_default=False,
        ),
    ]
