# Generated by Django 3.2.7 on 2021-09-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignationlog',
            old_name='reservation',
            new_name='assignation',
        ),
    ]
