# Generated by Django 3.2.19 on 2023-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_node_port_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='on_instance',
            field=models.CharField(default='all', help_text='The Instance this Agent is running on', max_length=1000),
        ),
    ]
