# Generated by Django 3.2.12 on 2022-07-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_auto_20220620_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provision',
            options={'permissions': [('can_link_to', 'Can link a reservation to a provision')]},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_assign', 'Can assign to this reservation')]},
        ),
    ]
