# Generated by Django 6.0.3 on 2026-09-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facade", "0002_implementation_required_locks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardwarerecord",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="action",
            name="pinned_by",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="health_check_interval",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="latest_event",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="on_instance",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="unique",
        ),
        migrations.RemoveField(
            model_name="blok",
            name="uri",
        ),
        migrations.RemoveField(
            model_name="blokdependency",
            name="assign_policy",
        ),
        migrations.RemoveField(
            model_name="blokdependency",
            name="prefered_instances",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="ui_tree",
        ),
        migrations.RemoveField(
            model_name="dashboardplacement",
            name="position",
        ),
        migrations.RemoveField(
            model_name="dependency",
            name="assign_policy",
        ),
        migrations.RemoveField(
            model_name="implementation",
            name="name",
        ),
        migrations.RemoveField(
            model_name="implementation",
            name="pinned_by",
        ),
        migrations.RemoveField(
            model_name="implementation",
            name="policy",
        ),
        migrations.RemoveField(
            model_name="implementation",
            name="release",
        ),
        migrations.RemoveField(
            model_name="resolution",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="session",
            name="active",
        ),
        migrations.RemoveField(
            model_name="state",
            name="retention_policy",
        ),
        migrations.RemoveField(
            model_name="state",
            name="value",
        ),
        migrations.RemoveField(
            model_name="task",
            name="hooks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="statusmessage",
        ),
        migrations.DeleteModel(
            name="AgentEvent",
        ),
        migrations.DeleteModel(
            name="HardwareRecord",
        ),
    ]
