# Generated by Django 6.0.3 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facade", "0003_drop_dead_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="The name a user gave this agent. It wins over the declared name, and registration never touches it.",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                default="Nana",
                help_text="The name the agent declares for itself; agentd writes it at every registration.",
                max_length=2000,
            ),
        ),
    ]
