# Generated by Django 3.1.7 on 2021-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_auto_20210304_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ManyToManyField(null=True, related_name='_service_parent_+', to='facade.Service'),
        ),
    ]
