# Generated by Django 3.2.2 on 2021-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_auto_20210520_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignation',
            name='node',
        ),
        migrations.RemoveField(
            model_name='assignation',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='assignation',
            name='template',
        ),
        migrations.AddField(
            model_name='assignation',
            name='context',
            field=models.JSONField(default={}, help_text='The Platform context'),
        ),
        migrations.AddField(
            model_name='assignation',
            name='extensions',
            field=models.JSONField(default={}, help_text='The Platform extensions'),
        ),
        migrations.AlterField(
            model_name='assignationlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level')], default='INFO', max_length=200),
        ),
        migrations.AlterField(
            model_name='provisionlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level')], default='INFO', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level')], default='INFO', max_length=200),
        ),
    ]
