# Generated by Django 3.1.7 on 2021-05-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_assignationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pod',
            field=models.ForeignKey(blank=True, help_text='The pod this reservation connects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='facade.pod'),
        ),
        migrations.CreateModel(
            name='Accessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get', models.CharField(help_text='A get accessor for this model', max_length=2000)),
                ('search', models.CharField(help_text='A selectable options query with a search Parameter', max_length=2000)),
                ('create', models.CharField(help_text='A create Parameter for this model', max_length=2000)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facade.datamodel')),
            ],
        ),
    ]
