# Generated by Django 3.2.4 on 2021-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_auto_20210622_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirrorrepository',
            old_name='mirror',
            new_name='url',
        ),
        migrations.AddField(
            model_name='mirrorrepository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
