# Generated by Django 3.1.7 on 2021-02-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facade.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0003_datapoint_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Repository', max_length=1000)),
                ('type', models.CharField(choices=[('local', 'Repository only exists locally'), ('mirror', 'Repository mirrors online')], default='local', help_text='Type of repository', max_length=200)),
                ('creator', models.ForeignKey(blank=True, help_text='The Person that created this repository', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generator', 'Generator'), ('function', 'Function')], default='function', help_text='Function, generator? Check async Programming Textbook', max_length=1000)),
                ('name', models.CharField(help_text='The cleartext name of this Node', max_length=1000)),
                ('package', models.CharField(help_text='Package (think Module)', max_length=1000)),
                ('interface', models.CharField(help_text='Interface (think Function)', max_length=1000)),
                ('description', models.TextField(help_text='A description for the Node')),
                ('image', models.ImageField(blank=True, help_text='A short description what this Node does', null=True, upload_to='')),
                ('inputs', facade.fields.InPortsField(default=list, help_text='Inputs for this Node')),
                ('outputs', facade.fields.OutPortsField(default=list, help_text='Outputs for this Node')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='facade.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('repository', 'package', 'interface'), name='package, interface, repository cannot be the same'),
        ),
    ]
