# Generated by Django 3.1.7 on 2021-03-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_commision'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commision',
            new_name='Commission',
        ),
    ]
