# Generated by Django 3.2.4 on 2021-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20210622_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='extenders',
            field=models.JSONField(help_text='Registered Extenders on this Model', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ROUTING', 'Routing (Reservation has been requested but no Topic found yet)'), ('PROVIDING', 'Providing (Reservation required the provision of a new worker)'), ('WAITING', 'Waiting (We are waiting for any assignable Topic to come online)'), ('REROUTING', 'Rerouting (State of provisions this reservation connects to have changed and require Retouring)'), ('DISCONNECTED', 'Disconnect (State of provisions this reservation connects to have changed and require Retouring)'), ('CANCELING', 'Cancelling (Reervation is currently being cancelled)'), ('ACTIVE', 'Active (Reservation is active and accepts assignments'), ('ERROR', 'Error (Reservation was not able to be performed (See StatusMessage)'), ('ENDED', 'Ended (Reservation was ended by the the Platform and is no longer active)'), ('CANCELLED', 'Cancelled (Reservation was cancelled by user and is no longer active)'), ('CRITICAL', 'Critical (Reservation failed with an Critical Error)')], default='ACTIVE', help_text='Current lifecycle of Reservation', max_length=300),
        ),
    ]
