# Generated by Django 6.0.3 on 2026-10-01 10:24

import django.contrib.postgres.fields
import django.db.models.functions.datetime
import django_choices_field.fields
import facade.enums.action
import facade.enums.agent
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("facade", "0004_agent_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signal",
            name="causing_root",
        ),
        migrations.AlterField(
            model_name="action",
            name="allow_probe",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="May this action be invoked as a probe (zero persistence, no history/replay/recovery)? Declared by the action author; the probe mutation refuses actions without it.",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="arg_count",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Pre-calculated number of root input ports",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="args",
            field=models.JSONField(
                db_default=[], default=list, help_text="Inputs for this Action"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="defined_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="embedding_model",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="idempotent",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this function idempotent. e.g can we run it multiple times without changing the data again ?",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="is_dev",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this Action a development Action",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("FUNCTION", "Function"), ("GENERATOR", "Generator")],
                choices_enum=facade.enums.action.ActionKindChoices,
                db_default="FUNCTION",
                default="FUNCTION",
                help_text="Function, generator? Will this function generate multiple results?",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(
                db_default="Unnamed Action",
                default="Unnamed Action",
                help_text="The cleartext name of this Action (e.g. 'Segment Image')",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="port_groups",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Intercae that we use to interpret the meta data",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="pure",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this function pure. e.g can we cache the result?",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="return_count",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Pre-calculated number of root output ports",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="returns",
            field=models.JSONField(
                db_default=[], default=list, help_text="Outputs for this Action"
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="scope",
            field=models.CharField(
                db_default="GLOBAL",
                default="GLOBAL",
                help_text="The scope of this Action. e.g. does the data it needs or produce live only in the scope of this Action or is it global or does it bridge data?",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="stateful",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this function stateful. e.g does it inherently depend on or change state (think physical devices)?",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="blocked",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If this Agent is blocked, it will not be used for provision, nor will it be able to provide",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="connected",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this Agent connected to the backend",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="installed_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="kind",
            field=models.CharField(
                choices=[
                    (facade.enums.agent.AgentKind["WEBSOCKET"], "WEBSOCKET"),
                    (facade.enums.agent.AgentKind["WEBHOOK"], "WEBHOOK"),
                ],
                db_default="WEBSOCKET",
                default=facade.enums.agent.AgentKind["WEBSOCKET"],
                help_text="The kind of this Agent",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="lease_epoch",
            field=models.BigIntegerField(
                db_default=0,
                default=0,
                help_text="Monotonic fencing token for the executor write-lease. Bumped on every claim (connect) and on every revoke (stale sweep). A connection carries the epoch it claimed and renews its lease with a compare-and-set on it, so a displaced or revoked connection's heartbeat matches no row and the connection terminates itself. Distinct from active_connection_id (a socket *name*, unique but not revocable) and active_session_id (the client-supplied *process* identity, which must stay equal across a reclaiming reconnect).",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                db_default="Nana",
                default="Nana",
                help_text="The name the agent declares for itself; agentd writes it at every registration.",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="argport",
            name="nullable",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="blok",
            name="components",
            field=models.JSONField(
                db_default=[], default=list, help_text="The UI schema for this Blok"
            ),
        ),
        migrations.AlterField(
            model_name="blok",
            name="demo_state",
            field=models.JSONField(
                db_default={},
                default=dict,
                help_text="The initial state for this Blok (to display in the ui a fake version)",
            ),
        ),
        migrations.AlterField(
            model_name="blok",
            name="diagnostics",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Non-fatal registration findings (rekuest_core Diagnostic), e.g. manifest util calls naming operations that neither the base catalog nor this blok's catalog provides. Replaced on every write.",
            ),
        ),
        migrations.AlterField(
            model_name="blokagentmapping",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="blokagentmapping",
            name="key",
            field=models.CharField(
                db_default="general",
                default="general",
                help_text="The reference of the dependency this mapping is for (e.g. imagej)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="blokagentmapping",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="blokdependency",
            name="action_demands",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="The action demands this dependency has to meet",
            ),
        ),
        migrations.AlterField(
            model_name="blokdependency",
            name="auto_resolvable",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.",
            ),
        ),
        migrations.AlterField(
            model_name="blokdependency",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="blokdependency",
            name="optional",
            field=models.BooleanField(
                db_default=False, default=False, help_text="Is this dependency optional"
            ),
        ),
        migrations.AlterField(
            model_name="blokdependency",
            name="state_demands",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="The state demands this dependency has to meet",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="defined_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="Date this Collection was created",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(
                help_text="The name of this Collection, unique within its organization",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="Date this Collection was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardplacement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="dashboardplacement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="action_demands",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="The action demands this dependency has to meet",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="auto_resolvable",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="optional",
            field=models.BooleanField(
                db_default=False, default=False, help_text="Is this dependency optional"
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="state_demands",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="The state demands this dependency has to meet",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="diagnostics",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Non-fatal registration findings (rekuest_core Diagnostic), e.g. validator/effect calls naming operations that neither the base catalog nor the definition's catalog provides. Replaced on every registration.",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="effects",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("NONE", "None (changes nothing)"),
                    ("REPEATABLE", "Repeatable (a second run leaves the same state)"),
                    ("UNKNOWN", "Unknown (no claim)"),
                    (
                        "IRREVERSIBLE",
                        "Irreversible (a second run happens again, in the real world)",
                    ),
                ],
                choices_enum=facade.enums.action.EffectsChoices,
                db_default="UNKNOWN",
                default="UNKNOWN",
                help_text="What running this implementation again would do to the world. Informational: shown to whoever decides about a lost task.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="execution",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PLAIN", "Plain"),
                    ("WORKFLOW", "Workflow (resumed from its journal)"),
                ],
                choices_enum=facade.enums.action.ExecutionChoices,
                db_default="PLAIN",
                default="PLAIN",
                help_text="How this implementation runs: a WORKFLOW may call other actions and is resumed from its journal when its agent dies.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="higher_order_config",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="Projection config for a higher-order implementation (only meaningful when ``higher_order_for`` is set). Describes how this wrapper's bound params + caller args + caller dependencies are remapped onto the wrapped (lower) implementation, and how the lower implementation's returns are unfolded back. Keys: ``bound`` (dict spread as the lower impl's named args), ``args_key`` (the lower arg port the remaining caller args are packed under), ``arg_map`` (explicit per-port arg remap), ``dependency_map`` (lower dep key -> source), ``return_map`` (lower return key -> wrapper return key).",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="needs_token",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether Rekuest mints a signed provenance token when this implementation is assigned. Default true (provenance-by-default); false skips minting for trivial/internal tasks.",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="params",
            field=models.JSONField(
                db_default={}, default=dict, help_text="Params for this Implementation"
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="tracks",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="A log of all the tasks that have been provisioned with this implementation, as well as their status and results",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="lock",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="lock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="materializedblok",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="materializedblok",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="memorydrawer",
            name="agent_minted",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="The agent minted this drawer's reference (a numbered SHELVE): the agent addresses it by resource_id, and COLLECT names it by resource_id. False for drawers of older agents, which reference the pk.",
            ),
        ),
        migrations.AlterField(
            model_name="memoryshelve",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="memoryshelve",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="patch",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The time this patch was created",
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="name",
            field=models.CharField(
                help_text="The name of this Protocol, unique within its organization",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="resolution",
            name="resolved_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="returnport",
            name="nullable",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="args",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="The args every run is assigned with",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Runs in a row that ended FAILED or CRITICAL; reset by a successful one",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="enabled",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="A disabled schedule creates no runs",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="ephemeral_runs",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Create the runs as ephemeral tasks (housekeeping sweeps: retention may drop them early)",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="timezone",
            field=models.CharField(
                db_default="UTC",
                default="UTC",
                help_text="The IANA zone a cron line is read in (DST included)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="claimed_pos",
            field=models.PositiveBigIntegerField(
                db_default=0,
                default=0,
                help_text="The position a backend is projecting right now (claimed_pos = projected_pos + 1 while one is in flight, else equal). Another backend waits for it, or takes it over once claimed_at is stale.",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The time this session was created",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="projected_pos",
            field=models.PositiveBigIntegerField(
                db_default=0,
                default=0,
                help_text="Every numbered frame of this session up to this position is handled: a resend at or below it is skipped, and JOURNAL_ACK claims it (docs/design/journal.md).",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The time this session was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="allow_quick",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Allow quick execution of this Shortcut (e.g. run without confirmation)",
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="args",
            field=models.JSONField(
                db_default=[], default=list, help_text="Inputs for this Shortcut"
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="bind_number",
            field=models.IntegerField(
                blank=True,
                db_default=0,
                default=0,
                help_text="Which shortcut should be bound to this Action by default. 0 means no binding",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="returns",
            field=models.JSONField(
                db_default=[], default=list, help_text="Outputs for this Shortcut"
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="saved_args",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="use_returns",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Use the result of this Shortcut (e.g. use the result in the next Shortcut)",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="descriptors",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="The object's descriptors (flat key → value), matched against triggers' conditions and ports' `requires`",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="received_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="signaldeclaration",
            name="descriptor_keys",
            field=models.JSONField(
                blank=True,
                db_default=[],
                default=list,
                help_text="The descriptor keys each signal carries",
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The time this snapshot was created",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="Date this State was first ever written to",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="Date this State was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="statedefinition",
            name="ports",
            field=models.JSONField(db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name="task",
            name="acted_on",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                db_default=[],
                default=list,
                help_text="Which structures were acted on in this task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="args",
            field=models.JSONField(
                blank=True, db_default={}, default=dict, help_text="The Args", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="capture",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Should we capture the logs and events of this Task (e.g. for debugging or auditing purposes)?",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="dependencies",
            field=models.JSONField(
                blank=True, db_default={}, default=dict, help_text="The Args", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="dependency",
            field=models.CharField(
                blank=True,
                db_default="general",
                default="general",
                help_text="The reference of the dependency this task was assigned to (e.g. imagej)",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="ephemeral",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this Task ephemeral (e.g. should it be deleted after its done or should it be kept for future reference)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Is this Task done (e.g. has it been completed and resulted in an error?)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_higher_order_child",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether this task is the lower child of a higher-order wrapper — its yields/terminals unfold onto the wrapper. Lets the event hot path skip the parent lookup for ordinary tasks.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="resumes",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="How often this workflow was sent again after its agent died. Capped: an agent that dies every time does not resume it forever.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="taskevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="taskinstruct",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_benchmark",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="passed",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="result",
            field=models.JSONField(blank=True, db_default={}, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="threedmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="threedmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="toolbox",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="toolbox",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="args",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="The other args of every run",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="conditions",
            field=models.JSONField(
                blank=True,
                db_default=[],
                default=list,
                help_text="Extra descriptor conditions (requires-style: key, operator, value)",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Firings in a row that could not create a run",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="enabled",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="A disabled trigger fires nothing",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="uicatalog",
            name="components",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Registered component specs (rekuest_core CatalogComponent): the names a ComponentNode.component may use and the props each accepts.",
            ),
        ),
        migrations.AlterField(
            model_name="uicatalog",
            name="operations",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Registered operation specs (rekuest_core CatalogOperation): the names a UtilCall.operation may use, their arguments and return kind.",
            ),
        ),
        migrations.AlterField(
            model_name="uicatalog",
            name="widget_defaults",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="Default widgets per port kind and/or structure identifier (rekuest_core WidgetDefault), applied by the UI to ports that declare no widget.",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="collection_unique_name_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="protocol",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="protocol_unique_name_per_organization",
            ),
        ),
    ]
