# Generated by Django 3.2.12 on 2022-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_alter_template_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='parent',
            new_name='provision',
        ),
    ]
