# Generated by Django 3.2.2 on 2021-05-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20210520_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='causing_provision',
            field=models.ForeignKey(blank=True, help_text='Was this Reservation caused by a Provision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_reservations', to='facade.provision'),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied (Assingment was rejected)'), ('ASSIGNED', 'Was able to assign to a pod'), ('PROGRESS', 'Progress (Assignment has current Progress)'), ('ERROR', 'Error (Retrieable)'), ('CRITICAL', 'Critical Error (No Retries available)'), ('CANCEL', 'Assinment is beeing cancelled'), ('CANCELING', 'Cancelling (Assingment is currently being cancelled)'), ('CANCELLED', 'Assignment has been cancelled.'), ('YIELD', 'Assignment yielded a value (only for Generators)'), ('DONE', 'Assignment has finished')], default='PENDING', help_text='Current lifecycle of Assignation', max_length=300),
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Request has been created and waits for its initial creation)'), ('PROVIDING', 'Providing (Request has been send to its Provider and waits for Result'), ('ACTIVE', 'Active (Provision is currently active)'), ('INACTIVE', 'Inactive (Provision is currently not active)'), ('CANCELING', 'Cancelling (Provisions is currently being cancelled)'), ('LOST', 'Lost (Subscribers to this Topic have lost their connection)'), ('RECONNECTING', 'Reconnecting (We are trying to Reconnect to this Topic)'), ('DENIED', 'Denied (Provision was rejected for this User)'), ('ERROR', 'Error (Reservation was not able to be performed (See StatusMessage)'), ('CRITICAL', 'Critical (Provision resulted in an critical system error)'), ('ENDED', 'Ended (Provision was cancelled by the Platform and will no longer create Topics)'), ('CANCELLED', 'Cancelled (Provision was cancelled by the User and will no longer create Topics)')], default='PENDING', help_text='Current lifecycle of Provision', max_length=300),
        ),
    ]
