# Generated by Django 3.1.7 on 2021-03-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20210315_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='pod',
            field=models.ForeignKey(blank=True, help_text='The pod this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision', to='facade.pod'),
        ),
    ]
