# Generated by Django 3.2.8 on 2022-02-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20220208_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='This Reservations app', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='facade.waiter'),
        ),
    ]
