# Generated by Django 3.2.8 on 2021-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_auto_20210922_0806'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='node',
            name='package, interface, repository cannot be the same',
        ),
        migrations.RemoveField(
            model_name='apprepository',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('repository', 'interface'), name='package, interface, repository cannot be the same'),
        ),
    ]
