# Generated by Django 3.1.7 on 2021-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.JSONField(default=[], help_text='The extensions to the protocol it provides'),
            preserve_default=False,
        ),
    ]
