# Generated by Django 3.1.7 on 2021-02-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facade.fields
import mars.names
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0004_auto_20210224_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(help_text='This providers Name', max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=mars.names.generate_random_name, help_text='A name for this Template', max_length=1000)),
                ('params', facade.fields.ParamsField(default=dict, help_text='Params for this Template')),
                ('version', models.CharField(help_text='A short descriptor for the kind of version', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='Who created this template on this instance', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(help_text='The node this template is implementatig', on_delete=django.db.models.deletion.CASCADE, to='facade.node')),
                ('provider', models.ForeignKey(help_text='The associated provider for this Template', on_delete=django.db.models.deletion.CASCADE, to='facade.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DOWN', 'Down'), ('ERROR', 'Error'), ('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='PENDING', help_text='Which lifecycle moment is this pod in', max_length=300)),
                ('mode', models.CharField(choices=[('producton', 'Production (runs in)'), ('debug', 'Debug (Pod is currently debugging)'), ('test', 'Pod is currently being tested')], default='producton', help_text='The mode this pod is running in', max_length=100)),
                ('name', models.CharField(default=mars.names.generate_random_name, help_text='A unique name for this pod', max_length=300, unique=True)),
                ('unique', models.UUIDField(default=uuid.uuid4, help_text='A Unique identifier for this Pod', unique=True)),
                ('channel', facade.fields.PodChannel(blank=True, help_text='The channel where the Pod listens to (is null if no listener)', max_length=5000, null=True)),
                ('statusmessage', models.CharField(blank=True, help_text='This pods Status', max_length=300)),
                ('template', models.ForeignKey(help_text='The template that created this pod', on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='facade.template')),
            ],
        ),
    ]
