# Generated by Django 3.1.7 on 2021-02-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facade.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0005_pod_provider_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', facade.fields.InputsField(blank=True, help_text='The Inputs', null=True)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Assignation', max_length=1000, unique=True)),
                ('outputs', facade.fields.OutputsField(blank=True, help_text='The Outputs', null=True)),
                ('callback', models.CharField(blank=True, help_text='The Callback queue once the Assignation has finished', max_length=1000, null=True)),
                ('progress', models.CharField(blank=True, help_text='The Progress queue once the Assignation has finished', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The creator is this assignation', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, help_text='The Node this assignation is having', null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.node')),
                ('pod', models.ForeignKey(blank=True, help_text='The pod this assignation connects to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.pod')),
                ('template', models.ForeignKey(blank=True, help_text='The Template this assignation is using', null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.template')),
            ],
        ),
    ]
