# Generated by Django 3.1.7 on 2021-03-04 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_service_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='internal',
        ),
        migrations.AlterField(
            model_name='provider',
            name='unique',
            field=models.CharField(default=uuid.uuid4, help_text='The Channel we are listening to', max_length=1000),
        ),
    ]
