# Generated by Django 6.0.3 on 2026-09-17 19:33

from django.db import migrations, models


def grandfather_open_tasks(apps, schema_editor):
    """Open tasks that predate the pickup bookkeeping count as picked up.

    The watchdog treats "dispatched long ago, never reported on" as lost and redelivers. For a
    task created before these columns existed that would be a false positive on every running
    task at deploy time (NULL ``picked_up_at`` on work that is happily executing) — and a
    redelivery could double-execute it. They stay covered by the disconnect/expiry paths.
    """
    Task = apps.get_model("facade", "Task")
    Task.objects.filter(is_done=False, picked_up_at__isnull=True).update(picked_up_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_statedefinition_hash_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dispatch_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0, help_text='How many times the Assign was dispatched (the pickup watchdog redelivers once, then fails the task).'),
        ),
        migrations.AddField(
            model_name='task',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text="When the Assign was last handed to the agent's transport. NULL = never pushed (virtual higher-order wrapper, or the push failed) — the pickup watchdog owns the retry.", null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='interrupt_at',
            field=models.DateTimeField(blank=True, help_text='Deadline after which an unconfirmed cancel is escalated to an interrupt (auto_interrupt / control deadline).', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, help_text='Last Progress report of a physical-effect task — only stamped while the progress lease is enabled.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, help_text='When the executing agent first reported ANYTHING about this task. ``latest_event_kind`` cannot answer this: Progress/Log/Yield never move it, so a healthy running task still reads QUEUED.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether this task was assigned in step mode — persisted so a redelivered Assign stays stepped.'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('is_done', False), ('picked_up_at__isnull', True)), fields=['dispatched_at'], name='task_unpicked_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('interrupt_at__isnull', False), ('is_done', False)), fields=['interrupt_at'], name='task_interrupt_due_idx'),
        ),
        migrations.RunPython(grandfather_open_tasks, migrations.RunPython.noop),
    ]
