# Generated by Django 3.1.7 on 2021-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_auto_20210505_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessor',
            name='create',
            field=models.TextField(blank=True, help_text='A create Parameter for this model', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='accessor',
            name='get',
            field=models.TextField(blank=True, help_text='A get accessor for this model', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='accessor',
            name='search',
            field=models.TextField(blank=True, help_text='A selectable options query with a search Parameter', max_length=2000, null=True),
        ),
    ]
