# Generated by Django 3.2.14 on 2022-07-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_rename_parent_reservation_provision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': [('can_provide_on', 'Can provide on this Agent')]},
        ),
    ]
