# Generated by Django 3.2.8 on 2022-02-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_reservation_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='This Assignation app', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.waiter'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='This Reservations app', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.waiter'),
        ),
    ]
