# Generated by Django 3.2.8 on 2021-10-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_auto_20211018_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='extensions',
            field=models.JSONField(default=list, help_text='The attached extensions for this Template', max_length=2000),
        ),
    ]
