# Generated by Django 3.2.4 on 2021-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_auto_20210914_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataModel',
            new_name='Structure',
        ),
        migrations.DeleteModel(
            name='Accessor',
        ),
    ]
