# Generated by Django 6.0.3 on 2026-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_database_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(db_default='Nana', default='Nana', help_text='The name the agent declares for itself, written at every registration.', max_length=2000),
        ),
    ]
