# Generated by Django 3.2.19 on 2023-05-28 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='reference',
            field=models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Assignation considering its parent', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.UniqueConstraint(fields=('reference', 'parent'), name='A unique reference per parent is required'),
        ),
    ]
