# Generated by Django 3.2.2 on 2021-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_auto_20210526_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, help_text='A Short Hand Way to identify this reservation for you', max_length=200, null=True),
        ),
    ]
