# Generated by Django 3.2.19 on 2023-05-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_auto_20230528_1400'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='Equal Reservation on this App by this Waiter is already in place',
        ),
    ]
