# Generated by Django 3.2.2 on 2021-05-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_reservation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionlog',
            name='message',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
