# Generated by Django 3.2.14 on 2022-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_alter_agent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='happy',
            field=models.BooleanField(default=False, help_text='Is this reservation happy? (aka: does it have as many linked provisions as desired'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='viable',
            field=models.BooleanField(default=False, help_text='Is this reservation viable? (aka: does it have as many linked provisions as minimal'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ROUTING', 'Routing (Reservation has been requested but no Topic found yet)'), ('NON_VIABLE', 'SHould signal that this reservation is non viable (has less linked provisions than minimalInstances)'), ('PROVIDING', 'Providing (Reservation required the provision of a new worker)'), ('WAITING', 'Waiting (We are waiting for any assignable Topic to come online)'), ('REROUTING', 'Rerouting (State of provisions this reservation connects to have changed and require Retouring)'), ('DISCONNECTED', 'Disconnect (State of provisions this reservation connects to have changed and require Retouring)'), ('DISCONNECT', 'Disconnect (State of provisions this reservation connects to have changed and require Retouring)'), ('CANCELING', 'Cancelling (Reervation is currently being cancelled)'), ('ACTIVE', 'Active (Reservation is active and accepts assignments'), ('ERROR', 'Error (Reservation was not able to be performed (See StatusMessage)'), ('ENDED', 'Ended (Reservation was ended by the the Platform and is no longer active)'), ('CANCELLED', 'Cancelled (Reservation was cancelled by user and is no longer active)'), ('CRITICAL', 'Critical (Reservation failed with an Critical Error)')], default='ROUTING', help_text='Current lifecycle of Reservation', max_length=300),
        ),
    ]
