# Generated by Django 3.2.8 on 2021-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_template_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.CharField(blank=True, help_text='A short descriptor for the kind of version', max_length=400, null=True),
        ),
    ]
