# Generated by Django 3.1.7 on 2021-02-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0006_assignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The Assignations parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.assignation'),
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, help_text='Params for the Policy (including Provider etc..)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Assignation', max_length=1000, unique=True)),
                ('creator', models.ForeignKey(help_text='This provision creator', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, help_text='The node this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='facade.node')),
                ('parent', models.ForeignKey(blank=True, help_text='The Provisions parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.provision')),
                ('pod', models.ForeignKey(blank=True, help_text='The pod this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='facade.pod')),
                ('template', models.ForeignKey(blank=True, help_text='The node this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='facade.template')),
            ],
        ),
    ]
