# Generated by Django 3.1.7 on 2021-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_auto_20210505_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='inward',
            field=models.CharField(help_text='Inward facing hostname (for Docker powered access)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='outward',
            field=models.CharField(help_text='Outward facing hostname for external clients', max_length=100, null=True),
        ),
    ]
