# Generated by Django 3.2.8 on 2022-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_auto_20220208_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pure',
            field=models.BooleanField(default=False, help_text='Is this function pure. e.g can we cache the result?'),
        ),
    ]
