# Generated by Django 3.2.14 on 2022-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_auto_20220726_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='lost',
            field=models.BooleanField(default=True, help_text='Is the connection to this Provision lost?'),
        ),
    ]
