# Generated by Django 3.2.8 on 2021-10-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_alter_template_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='title',
            field=models.CharField(blank=True, help_text='A Short Hand Way to identify this reservation for you', max_length=200, null=True),
        ),
    ]
