# Generated by Django 3.1.7 on 2021-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_auto_20210506_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='port',
            field=models.IntegerField(help_text='Listening port', null=True),
        ),
    ]
