# Generated by Django 6.0.3 on 2026-10-03 17:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('facade', '0007_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='catch_up',
            field=models.BooleanField(db_default=False, default=False, help_text='Run the slots missed while takt was down or a run was open, late and in order, instead of skipping them'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, help_text='What the rule is for', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='No run is planned after this moment; null = never ends', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='When `last_error` was written', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='When it last created a run', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_slot_at',
            field=models.DateTimeField(blank=True, help_text='The slot of the run planned last: where catch-up continues from', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_runs',
            field=models.PositiveIntegerField(blank=True, help_text='No run is planned once it created this many; null = no limit', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='overlap',
            field=models.CharField(choices=[('SKIP', 'Skip'), ('ALLOW', 'Allow')], db_default='SKIP', default='SKIP', help_text='SKIP: the next run waits for the previous to finish. ALLOW: runs may overlap.', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='run_count',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Runs it created, counted by takt (retention deletes old runs, this stays)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wire_key',
            field=models.CharField(blank=True, help_text="What the wiregram's document calls this rule", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='debounce_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Fire at most once per object within this many seconds (the first signal fires, later ones are rejected); null = every signal', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='description',
            field=models.TextField(blank=True, help_text='What the rule is for', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Nothing fires after this moment; null = never ends', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='When `last_error` was written', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='When it last created a run', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='max_runs',
            field=models.PositiveIntegerField(blank=True, help_text='Nothing fires once it created this many; null = no limit', null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='run_count',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Runs it created, counted by takt (retention deletes old runs, this stays)'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='wire_key',
            field=models.CharField(blank=True, help_text="What the wiregram's document calls this rule", max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Firing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('FIRED', 'Fired'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], help_text='FIRED: a run was created. REJECTED: the trigger did not apply. FAILED: creating the run failed.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why it was rejected or failed; for a replay, that it was one', null=True)),
                ('replay', models.BooleanField(db_default=False, default=False, help_text='Fired by hand on a stored signal, not by the signal arriving')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('signal', models.ForeignKey(help_text='The signal', on_delete=django.db.models.deletion.CASCADE, related_name='firings', to='facade.signal')),
                ('task', models.ForeignKey(blank=True, help_text='The run it created, while that run exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firings', to='facade.task')),
                ('trigger', models.ForeignKey(help_text='The trigger that was tried on it', on_delete=django.db.models.deletion.CASCADE, related_name='firings', to='facade.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Wiregram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='What the document calls itself; importing the same key again updates this wiregram', max_length=200)),
                ('name', models.CharField(help_text='A human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What the document says it is for', null=True)),
                ('document', models.JSONField(blank=True, db_default={}, default=dict, help_text='The document as it was last imported')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('caller', models.ForeignKey(help_text='Who imported it last: the runs of its rules are assigned as this identity', on_delete=django.db.models.deletion.CASCADE, related_name='wiregrams', to='facade.caller')),
                ('organization', models.ForeignKey(help_text='The organization that imported it', on_delete=django.db.models.deletion.CASCADE, related_name='wiregrams', to='authentikate.organization')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='wiregram',
            field=models.ForeignKey(blank=True, help_text='The wiregram that owns this rule, if it was imported with one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='facade.wiregram'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='wiregram',
            field=models.ForeignKey(blank=True, help_text='The wiregram that owns this rule, if it was imported with one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='facade.wiregram'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('wiregram__isnull', False)), fields=('wiregram', 'wire_key'), name='schedule_unique_wire_key'),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.UniqueConstraint(condition=models.Q(('wiregram__isnull', False)), fields=('wiregram', 'wire_key'), name='trigger_unique_wire_key'),
        ),
        migrations.AddIndex(
            model_name='firing',
            index=models.Index(fields=['trigger', '-created_at'], name='firing_trigger_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='firing',
            constraint=models.UniqueConstraint(condition=models.Q(('replay', False)), fields=('signal', 'trigger'), name='firing_unique_per_signal_trigger'),
        ),
        migrations.AddConstraint(
            model_name='wiregram',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='wiregram_unique_key_per_organization'),
        ),
    ]
