# Generated by Django 3.1.7 on 2021-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_auto_20210224_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied (Assingment was rejected)'), ('ASSIGNED', 'Was able to assign to a pod'), ('PROGRESS', 'Progress (Assignment has current Progress)'), ('ERROR', 'Error (Retrieable)'), ('CRITICAL', 'Critical Error (No Retries available)'), ('CANCEL', 'Assinment is beeing cancelled'), ('CANCELLED', 'Assignment has been cancelled.'), ('YIELD', 'Assignment yielded a value (only for Generators)'), ('DONE', 'Assignment has finished')], default='PENDING', help_text='Current lifecycle of Assignation', max_length=300),
        ),
        migrations.AddField(
            model_name='assignation',
            name='statusmessage',
            field=models.CharField(default='', help_text='Clear Text status of the Assignation as for now', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provision',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied (Provision was rejected)'), ('PROGRESS', 'Progress (Provision has current Progress)'), ('ERROR', 'Error (Retrieable)'), ('CRITICAL', 'Critical Error (No Retries available)'), ('CANCEL', 'Provision is beeing cancelled'), ('CANCELLED', 'Provision has been cancelled.'), ('DONE', 'Provision has finished (pod is available and will connect)')], default='PENDING', help_text='Current lifecycle of Provision', max_length=300),
        ),
        migrations.AddField(
            model_name='provision',
            name='statusmessage',
            field=models.CharField(default='', help_text='Clear Text status of the Provision as for now', max_length=1000),
            preserve_default=False,
        ),
    ]
