# Generated by Django 3.1.7 on 2021-03-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_auto_20210315_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='pod',
            field=models.OneToOneField(blank=True, help_text='The pod this provision connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision', to='facade.pod'),
        ),
    ]
