# Generated by Django 3.2.19 on 2023-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_remove_reservation_equal reservation on this app by this waiter is already in place'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('reference', 'node', 'waiter'), name='Equal Reservation on this App by this Waiter is already in place'),
        ),
    ]
