# Generated by Django 3.2.8 on 2021-10-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_provision_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='provision',
            field=models.ForeignKey(blank=True, help_text='Which Provision did we end up being assigned to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='facade.provision'),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RETURNED', 'Assignation Returned (Only for Functions)'), ('DENIED', 'Denied (Assingment was rejected)'), ('ASSIGNED', 'Was able to assign to a pod'), ('PROGRESS', 'Progress (Assignment has current Progress)'), ('RECEIVED', 'Received (Assignment was received by an agent)'), ('ERROR', 'Error (Retrieable)'), ('CRITICAL', 'Critical Error (No Retries available)'), ('CANCEL', 'Assinment is beeing cancelled'), ('CANCELING', 'Cancelling (Assingment is currently being cancelled)'), ('CANCELLED', 'Assignment has been cancelled.'), ('YIELD', 'Assignment yielded a value (only for Generators)'), ('DONE', 'Assignment has finished')], default='PENDING', help_text='Current lifecycle of Assignation', max_length=300),
        ),
    ]
