# Generated by Django 3.1.7 on 2021-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_auto_20210315_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignation',
            name='inputs',
        ),
        migrations.AddField(
            model_name='assignation',
            name='args',
            field=models.JSONField(blank=True, help_text='The Args', null=True),
        ),
        migrations.AddField(
            model_name='assignation',
            name='kwargs',
            field=models.JSONField(blank=True, help_text='The Kwargs', null=True),
        ),
        migrations.AddField(
            model_name='assignation',
            name='returns',
            field=models.JSONField(blank=True, help_text='The Returns', null=True),
        ),
    ]
