# Generated by Django 3.1.7 on 2021-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_auto_20210224_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignation',
            name='statusmessage',
            field=models.CharField(blank=True, help_text='Clear Text status of the Assignation as for now', max_length=1000),
        ),
        migrations.AlterField(
            model_name='provision',
            name='statusmessage',
            field=models.CharField(blank=True, help_text='Clear Text status of the Provision as for now', max_length=1000),
        ),
    ]
