# Generated by Django 3.2.8 on 2021-10-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_auto_20211025_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='mode',
            field=models.CharField(choices=[('DEBUG', 'Debug Mode (Node might be constantly evolving)'), ('PRODUCTION', 'Production Mode (Node might be constantly evolving)')], default='PRODUCTION', help_text='The Deployment Mode for this Provisions', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='provision',
            field=models.ForeignKey(blank=True, help_text='Which Provision did we end up being assigned to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.provision'),
        ),
        migrations.AlterField(
            model_name='assignationlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level'), ('YIELD', 'YIELD Level'), ('CANCEL', 'Cancel Level'), ('RETURN', 'YIELD Level'), ('DONE', 'Done Level')], default='INFO', max_length=200),
        ),
        migrations.AlterField(
            model_name='provisionlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level'), ('YIELD', 'YIELD Level'), ('CANCEL', 'Cancel Level'), ('RETURN', 'YIELD Level'), ('DONE', 'Done Level')], default='INFO', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL Level'), ('INFO', 'INFO Level'), ('DEBUG', 'DEBUG Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level'), ('YIELD', 'YIELD Level'), ('CANCEL', 'Cancel Level'), ('RETURN', 'YIELD Level'), ('DONE', 'Done Level')], default='INFO', max_length=200),
        ),
    ]
