# Generated by Django 3.1.7 on 2021-03-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_auto_20210315_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='created_by',
            field=models.ForeignKey(help_text='The provision that created this pod', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_pods', to='facade.provision'),
        ),
    ]
