# Generated by Django 6.0.3 on 2026-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_descriptors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='lease_epoch',
        ),
        migrations.AlterField(
            model_name='agent',
            name='active_connection_id',
            field=models.CharField(blank=True, help_text="Identifies the websocket connection currently owning this Agent, and is the fencing token of the executor write-lease: written on every claim (connect), cleared on every revoke (stale sweep). A connection renews its lease with a compare-and-set on it, so a displaced or revoked connection's heartbeat matches no row and the connection terminates itself.", max_length=1000, null=True),
        ),
    ]
