# Generated by Django 3.1.7 on 2021-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_auto_20210224_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(help_text='The Client ID of the App connecting', max_length=600)),
                ('name', models.CharField(help_text='The name of this communicator', max_length=600)),
            ],
        ),
        migrations.AddConstraint(
            model_name='communicator',
            constraint=models.UniqueConstraint(fields=('app', 'name'), name='Unique communicator for app and Name'),
        ),
    ]
