# Generated by Django 3.2.14 on 2022-08-16 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_rename_lost_provision_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hash',
            field=models.CharField(default=uuid.uuid4, help_text='The hash of the Reservation', max_length=1000, unique=True),
        ),
    ]
