# Generated by Django 3.2.19 on 2023-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_testcase_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='facade.node'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='facade.testcase'),
        ),
    ]
