# Generated by Django 3.1.7 on 2021-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_pod_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='callback',
            field=models.CharField(blank=True, help_text='Callback', max_length=1000),
        ),
        migrations.AddField(
            model_name='provision',
            name='provider',
            field=models.CharField(blank=True, help_text='Provider', max_length=1000),
        ),
    ]
