# Generated by Django 3.1.7 on 2021-02-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_auto_20210225_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='communicator',
            field=models.ForeignKey(default=1, help_text='The Communicator of this Pod', on_delete=django.db.models.deletion.CASCADE, to='facade.communicator'),
            preserve_default=False,
        ),
    ]
