# Generated by Django 3.1.7 on 2021-02-25 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0011_pod_communicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='communicator',
        ),
        migrations.AddField(
            model_name='provider',
            name='app',
            field=models.CharField(default='internal', help_text='Do we have an external client? The Client ID of the App connecting, Default to internal if this is internal', max_length=600),
        ),
        migrations.AddField(
            model_name='provider',
            name='unique',
            field=models.CharField(default=uuid.uuid4, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('app', 'name'), name='Only one provider per app'),
        ),
        migrations.DeleteModel(
            name='Communicator',
        ),
    ]
