# Generated by Django 3.1.7 on 2021-03-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0011_auto_20210315_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provision',
            old_name='provider',
            new_name='progress',
        ),
    ]
