# Generated by Django 3.1.7 on 2021-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0012_auto_20210225_1059'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('node', 'params'), name='Exactly the same Template exists (consider overrwirting)'),
        ),
    ]
