# Generated by Django 3.1.7 on 2021-03-22 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0012_auto_20210315_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, help_text='Params for the Policy (including Provider etc..)', null=True)),
                ('channel', models.CharField(max_length=6000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied (Provision was rejected)'), ('PROGRESS', 'Progress (Provision has current Progress)'), ('ERROR', 'Error (Retrieable)'), ('CRITICAL', 'Critical Error (No Retries available)'), ('CANCEL', 'Provision is beeing cancelled'), ('CANCELLED', 'Provision has been cancelled.'), ('DONE', 'Provision has finished (pod is available and will connect)')], default='PENDING', help_text='Current lifecycle of Provision', max_length=300)),
                ('statusmessage', models.CharField(blank=True, help_text='Clear Text status of the Provision as for now', max_length=1000)),
                ('callback', models.CharField(blank=True, help_text='Callback', max_length=1000)),
                ('progress', models.CharField(blank=True, help_text='Provider', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Assignation', max_length=1000, unique=True)),
                ('creator', models.ForeignKey(help_text='This provision creator', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, help_text='The node this reservation connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.node')),
                ('parent', models.ForeignKey(blank=True, help_text='The Provisions parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.reservation')),
                ('pod', models.ForeignKey(blank=True, help_text='The pod this reservation connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.pod')),
                ('template', models.ForeignKey(blank=True, help_text='The template this reservation connects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.template')),
            ],
        ),
    ]
