# Generated by Django 3.2.14 on 2022-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0013_remove_node_kwargs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='Equal Reservation on this App by this Waiter is already in place',
        ),
        migrations.AlterField(
            model_name='assignation',
            name='args',
            field=models.JSONField(blank=True, default=list, help_text='The Args', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='interfaces',
            field=models.JSONField(default=[], help_text='Intercae that we sss to'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('reference', 'node', 'waiter'), name='Equal Reservation on this App by this Waiter is already in place'),
        ),
    ]
