# Generated by Django 3.1.7 on 2021-03-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_assignation_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provision',
            name='node',
        ),
    ]
