# Generated by Django 3.1.7 on 2021-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_auto_20210225_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this Provider active right now?'),
        ),
    ]
