# Generated by Django 3.2.14 on 2022-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_auto_20220820_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference',
            field=models.CharField(default='default', help_text='The Unique identifier of this Assignation', max_length=1000),
        ),
    ]
