# Generated by Django 3.2.19 on 2023-06-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_auto_20230608_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_test_for',
            field=models.ManyToManyField(blank=True, to='facade.Node'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='facade.template'),
        ),
    ]
