# Generated by Django 3.2.14 on 2022-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0015_alter_reservation_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provision',
            name='provision',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='context',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='extensions',
        ),
    ]
