# Generated by Django 3.2.19 on 2023-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0015_auto_20230609_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_test_for',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='_facade_node_is_test_for_+', to='facade.Node'),
        ),
    ]
