# Generated by Django 3.1.7 on 2021-02-25 13:54

from django.db import migrations, models
import mars.names


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0015_provider_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='template',
            name='Exactly the same Template exists (consider overrwirting)',
        ),
        migrations.AlterField(
            model_name='pod',
            name='name',
            field=models.CharField(default=mars.names.generate_random_name, help_text='A unique name for this pod', max_length=300),
        ),
        migrations.AddConstraint(
            model_name='pod',
            constraint=models.UniqueConstraint(fields=('template', 'name'), name='A pod needs to uniquely identify with a name for a template'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('node', 'params'), name='A template has unique params for every node'),
        ),
    ]
