# Generated by Django 6.0.3 on 2026-09-29 19:43

import django_choices_field.fields
import facade.enums.action
from django.db import migrations, models


def carry_the_effect_class_over(apps, schema_editor):
    """PHYSICAL said what IRREVERSIBLE says; NONE was only ever the default, so it claimed nothing."""
    Implementation = apps.get_model("facade", "Implementation")
    Implementation.objects.filter(effect="PHYSICAL").update(effects="IRREVERSIBLE")


def carry_it_back(apps, schema_editor):
    Implementation = apps.get_model("facade", "Implementation")
    Implementation.objects.filter(effects="IRREVERSIBLE").update(effect="PHYSICAL")


class Migration(migrations.Migration):

    dependencies = [
        ("facade", "0015_agent_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="code_hash",
            field=models.CharField(
                blank=True,
                help_text="A hash of the implementation's code. A workflow is only resumed by an implementation with the same hash.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="effects",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("NONE", "None (changes nothing)"),
                    ("REPEATABLE", "Repeatable (a second run leaves the same state)"),
                    ("UNKNOWN", "Unknown (no claim)"),
                    (
                        "IRREVERSIBLE",
                        "Irreversible (a second run happens again, in the real world)",
                    ),
                ],
                choices_enum=facade.enums.action.EffectsChoices,
                default="UNKNOWN",
                help_text="What running this implementation again would do to the world. Informational: shown to whoever decides about a lost task.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="execution",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PLAIN", "Plain"),
                    ("WORKFLOW", "Workflow (resumed from its journal)"),
                ],
                choices_enum=facade.enums.action.ExecutionChoices,
                default="PLAIN",
                help_text="How this implementation runs: a WORKFLOW may call other actions and is resumed from its journal when its agent dies.",
                max_length=8,
            ),
        ),
        migrations.RunPython(carry_the_effect_class_over, carry_it_back),
        migrations.RemoveField(
            model_name="implementation",
            name="effect",
        ),
    ]
