# Generated by Django 3.1.7 on 2021-02-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facade', '0016_auto_20210225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(help_text='The provide might be limited to a instance like ImageJ belonging to a specific person. Is nullable for backend users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provider',
            name='app',
            field=models.CharField(default=uuid.uuid4, help_text='Do we have an external client? The Client ID of the App connecting, Default to internal if this is internal', max_length=600),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('app', 'user'), name='No multiple Providers for same App and User allowed'),
        ),
    ]
