# Generated by Django 3.1.7 on 2021-03-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0017_auto_20210326_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='created_by',
            new_name='provision',
        ),
        migrations.RemoveField(
            model_name='provision',
            name='pod',
        ),
    ]
