# Generated by Django 3.2.14 on 2022-08-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0017_alter_reservation_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='node',
            field=models.ForeignKey(help_text='The node this reservation connects', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.node'),
        ),
    ]
