# Generated by Django 3.2.19 on 2023-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0017_alter_node_is_test_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(help_text='The name of this Collection', max_length=1000, unique=True)),
                ('description', models.TextField(help_text='A description for the Collection')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='collections',
            field=models.ManyToManyField(help_text='The collections this Node belongs to', related_name='nodes', to='facade.Collection'),
        ),
    ]
