# Generated by Django 3.2.19 on 2023-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0018_auto_20230627_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Protocol', max_length=1000, unique=True)),
                ('description', models.TextField(help_text='A description for the Protocol')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='protocols',
            field=models.ManyToManyField(blank=True, help_text='The protocols this Node implements', related_name='nodes', to='facade.Node'),
        ),
    ]
