# Generated by Django 3.1.7 on 2021-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0018_auto_20210326_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='callback',
            field=models.CharField(blank=True, help_text='Callback', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='progress',
            field=models.CharField(blank=True, help_text='Provider', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='callback',
            field=models.CharField(blank=True, help_text='Callback', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='progress',
            field=models.CharField(blank=True, help_text='Provider', max_length=1000, null=True),
        ),
    ]
