# Generated by Django 3.2.14 on 2022-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0018_alter_reservation_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='meta',
            field=models.JSONField(default=dict, help_text='Meta data about this Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='interfaces',
            field=models.JSONField(default=list, help_text='Intercae that we sss to'),
        ),
    ]
