# Generated by Django 3.2.19 on 2023-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0019_auto_20230709_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='protocols',
            field=models.ManyToManyField(blank=True, help_text='The protocols this Node implements', related_name='nodes', to='facade.Protocol'),
        ),
    ]
