# Generated by Django 3.2.14 on 2022-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0019_auto_20220823_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='interfaces',
            field=models.JSONField(default=list, help_text='Intercae that we use to interpret the meta data'),
        ),
        migrations.AlterField(
            model_name='node',
            name='meta',
            field=models.JSONField(blank=True, help_text='Meta data about this Node', null=True),
        ),
    ]
