# Generated by Django 3.2.14 on 2022-08-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0020_auto_20220823_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='facade.repository'),
        ),
    ]
