# Generated by Django 3.2.14 on 2022-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0021_alter_node_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='progress',
            field=models.IntegerField(blank=True, help_text='The progress of this assignation', null=True),
        ),
    ]
