# Generated by Django 6.0.3 on 2026-10-06 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatalayerStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="The object-store URI of the file",
                        max_length=1000,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The object key/path within the datalayer bucket.",
                        max_length=1000,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        help_text="The datalayer bucket/service this store belongs to.",
                        max_length=1000,
                    ),
                ),
                (
                    "original_file_name",
                    models.CharField(
                        blank=True,
                        help_text="The original client-provided file name.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="The client-provided content type for the uploaded file.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "populated",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Whether the store has been populated with a valid path and is ready for use.",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user that created this store.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datalayer_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this store owns. Access is scoped to it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datalayer_stores",
                        to="authentikate.organization",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaStore",
            fields=[
                (
                    "datalayerstore_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="datalayer.datalayerstore",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("datalayer.datalayerstore",),
        ),
    ]
