# Generated by Django 6.0.3 on 2026-09-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parquetstore",
            name="datalayerstore_ptr",
        ),
        migrations.RemoveField(
            model_name="zarrstore",
            name="datalayerstore_ptr",
        ),
        migrations.DeleteModel(
            name="BigFileStore",
        ),
        migrations.DeleteModel(
            name="ParquetStore",
        ),
        migrations.DeleteModel(
            name="ZarrStore",
        ),
    ]
