# Generated by Django 6.0.3 on 2026-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0002_drop_dead_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalayerstore",
            name="populated",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether the store has been populated with a valid path and is ready for use.",
            ),
        ),
    ]
