//! `rekuest_core::units` answers what the Python server's `rekuest_core/units.py` answers.
//!
//! `fixtures/units.json` is generated by `fixtures/generate_units.py` with the pint the server
//! pins (0.25.3): every unit name, symbol and alias of the default registry, plurals, prefixed
//! forms, dimensions, compound and preprocessed spellings, and invalid expressions.

use rekuest_core::units::dimensionality_of;
use serde_json::Value;

/// Expressions whose answer is knowingly not Python's, with why.
const KNOWN_GAPS: &[(&str, &str)] = &[];

#[test]
fn every_expression_answers_like_python() {
    let fixture: Value = serde_json::from_str(include_str!("fixtures/units.json")).unwrap();
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 400, "the fixture shrank");

    let mut mismatches = vec![];
    for case in cases {
        let expression = case["expression"].as_str().unwrap();
        if KNOWN_GAPS.iter().any(|(gap, _)| *gap == expression) {
            continue;
        }
        let got = dimensionality_of(expression);
        match (case.get("dimensionality").and_then(Value::as_str), &got) {
            (Some(expected), Ok(actual)) if expected == actual => {}
            (None, Err(_)) => {}
            (expected, _) => mismatches.push(format!(
                "{expression:?}: python {} / rust {}",
                expected
                    .map(str::to_owned)
                    .unwrap_or_else(|| format!("error {}", case["error"])),
                match &got {
                    Ok(dims) => dims.clone(),
                    Err(e) => format!("error {}", e.reason),
                }
            )),
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} expressions differ from Python:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches.join("\n")
    );
}
